version: "3.8"

services:
  db:
    image: postgres
    container_name: pgdocker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: bfm
    ports:
      - "5432:5432"

  api:
    build: ./api
    container_name: api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: docker
      DB_NAME: bfm
